Repository grafana/xk6-browser, pull requests merged in 2022-10, with the labels that each got.

#564 Refactor to NewRequestParams
  common/network_manager.go
  common/request.go
  common/request_test.go
Labels: refactor

#579 Fix onLoadingFinished reqFromParent nil check
  common/network_manager.go
Labels: bug

#595 Update to latest k6
  common/frame.go
  common/network_manager.go
  go.mod
  go.sum
Labels: maintenance

#607 Update go.mod
  go.mod
  go.sum
Labels: maintenance

#578 Fix wait for networkIdle lifecycle event
  common/frame.go
  common/frame_options.go
  common/frame_session.go
  common/page_options.go
  tests/frame_test.go
  tests/static/prolonged_network_idle.html
  tests/static/prolonged_network_idle_10.html
Labels: bug, events

#606 Add iteration ID field to log events
  chromium/browser_type.go
  common/context.go
  common/helpers_test.go
  common/network_manager.go
  common/network_manager_test.go
  common/response.go
  log/logger.go
  tests/browser_test.go
Labels: tooling

#615 Optimize TestPageScreenshotFullpage
  tests/page_test.go
Labels: tests, optimization
