Repository grafana/xk6-browser, pull requests merged in 2022-05, with the labels that each got.

#296 Add initial roadmap document
  ROADMAP.md
Labels: documentation

#265 Release notes v0.3.0
  release notes/v0.3.0.md
Labels: documentation

#314 Add grant permissions support to BrowserContext
  common/browser_context.go
  common/browser_context_options.go
  common/browser_context_options_test.go
  examples/grant_permission.js
Labels: bug, feature

#310 Implement page.locator(selector)
  api/frame.go
  api/locator.go
  api/page.go
  common/frame.go
  common/locator.go
  common/logger.go
  common/page.go
  common/page_test.go
Labels: feature

#316 Fix gci linter config
  .golangci.yml
  chromium/browser_type.go
  chromium/browser_type_test.go
  common/browser.go
  common/browser_context.go
  common/connection_test.go
  common/element_handle.go
  common/element_handle_test.go
  common/execution_context.go
  common/frame.go
  common/frame_manager.go
  common/frame_session.go
  common/helpers.go
  common/helpers_test.go
  common/js_handle.go
  common/keyboard.go
  common/mouse.go
  common/network_manager.go
  common/network_manager_test.go
  common/page.go
  common/request.go
  common/request_test.go
  common/response.go
  common/session_test.go
  common/touchscreen.go
  common/types.go
  common/worker.go
  main.go
  tests/browser_context_options_test.go
  tests/element_handle_test.go
  tests/frame_manager_test.go
  tests/keyboard_test.go
  tests/launch_options_slowmo_test.go
  tests/network_manager_test.go
  tests/test_browser.go
  tests/test_context.go
  tests/ws/server.go
Labels: bug, ci

#315 Refactor k6 VU and tests
  chromium/browser_type.go
  common/browser.go
  common/browser_context.go
  common/browser_context_options.go
  common/browser_context_options_test.go
  common/context.go
  common/element_handle_options.go
  common/execution_context.go
  common/frame.go
  common/frame_manager.go
  common/frame_options.go
  common/frame_options_test.go
  common/frame_session.go
  common/frame_test.go
  common/helpers.go
  common/helpers_test.go
  common/keyboard_options.go
  common/launch.go
  common/launch_test.go
  common/mouse_options.go
  common/network_manager.go
  common/network_manager_test.go
  common/page.go
  common/page_options.go
  common/remote_object.go
  common/remote_object_test.go
  common/request.go
  common/request_test.go
  common/response.go
  common/types.go
  k6/context.go
  k6/k6test/vu.go
  main.go
  tests/browser_context_options_test.go
  tests/browser_test.go
  tests/element_handle_test.go
  tests/frame_manager_test.go
  tests/js_handle_get_properties_test.go
  tests/launch_options_slowmo_test.go
  tests/network_manager_test.go
  tests/page_test.go
  tests/test_browser.go
Labels: refactor

#317 Remove unused modules
  go.mod
  go.sum
Labels: maintenance

#318 Add locator.click([options])
  api/frame.go
  api/locator.go
  common/frame.go
  common/helpers.go
  common/locator.go
  tests/locator_test.go
  tests/static/strict_link.html
Labels: feature

#319 Refactor k6 facilities
  chromium/browser_type.go
  common/browser.go
  common/browser_context.go
  common/context.go
  common/element_handle.go
  common/frame.go
  common/frame_manager.go
  common/frame_session.go
  common/helpers.go
  common/js_handle.go
  common/keyboard.go
  common/locator.go
  common/metrics.go
  common/mouse.go
  common/network_manager.go
  common/page.go
  common/remote_object.go
  common/request.go
  common/response.go
  common/touchscreen.go
  k6/context.go
  k6/metrics.go
  k6/panic.go
  main.go
  tests/element_handle_test.go
  tests/test_browser.go
Labels: refactor

#320 Refactor logger into its own package
  chromium/browser_type.go
  common/barrier_test.go
  common/browser.go
  common/browser_context.go
  common/browser_process.go
  common/browser_test.go
  common/connection.go
  common/connection_test.go
  common/execution_context.go
  common/frame.go
  common/frame_manager.go
  common/frame_session.go
  common/frame_test.go
  common/helpers.go
  common/helpers_test.go
  common/js_handle.go
  common/locator.go
  common/network_manager.go
  common/network_manager_test.go
  common/page.go
  common/response.go
  common/session.go
  common/session_test.go
  log/logger.go
  log/logger_test.go
Labels: refactor
