Repository grafana/xk6-browser, pull requests merged in 2022-09, with the labels that each got.

#531 Fix data race in frame url while logging
  common/page.go
Labels: bug

#532 Fix parallel locator tests
  tests/locator_test.go
  tests/static/locators.html
Labels: bug, tests

#556 Docker example
  Dockerfile
  README.md
  docker-compose.yaml
Labels: documentation, user experience
