Repository grafana/xk6-browser, pull requests merged in 2022-11, with the labels that each got.

#620 Log when a launch option is set to null
  chromium/browser_type.go
  common/browser_options.go
  common/browser_options_test.go
  common/browser_test.go
  common/helpers_test.go
  common/network_manager.go
  common/network_manager_test.go
  common/response.go
  log/logger.go
Labels: user experience

#629 Fix the ip address in browser_args
  examples/browser_args.js
Labels: bug, tests

#630 Add mutex to prevent data race on pendingDoc and use mutex when reading frame.inflightRequests
  common/frame.go
  common/frame_manager.go
Labels: bug

#628 Fix WaitForLoadState and add tests
  common/frame.go
  common/helpers.go
  tests/lifecycle_wait_test.go
  tests/page_test.go
  tests/static/wait_for_nav_lifecycle.html
Labels: bug

#634 Fix a race condition with logCache.entries
  tests/browser_test.go
Labels: bug, tests

#624 Release notes v0.6.0
  release notes/v0.6.0.md
Labels: documentation

#663 dismiss dialog box automatically
  common/frame_session.go
  tests/frame_test.go
  tests/static/dialog.html
Labels: feature

#647 Refactor lifecycle tests and add any missing tests
  tests/lifecycle_wait_test.go
  tests/static/lifecycle.html
  tests/static/lifecycle_main_frame.html
  tests/static/lifecycle_no_ping_js.html
  tests/static/prolonged_network_idle.html
  tests/static/reload_lifecycle.html
Labels: tests
