Repository grafana/xk6-browser, pull requests merged in 2022-02, with the labels that each got.

#213 Make session an anonymous interface within NetworkManager
  common/network_manager.go
  common/session.go
Labels: refactor

#212 Refactor/elementhandle evaluate calls after revert
  common/element_handle.go
  common/execution_context.go
  common/frame.go
  common/frame_test.go
  common/js_handle.go
  common/page.go
  common/screenshotter.go
  tests/element_handle_click_test.go
Labels: refactor

#211 Fix general linter errors
  .github/workflows/all.yaml
  chromium/allocator.go
  chromium/browser_type.go
  common/browser_context.go
  common/element_handle.go
  common/frame.go
  common/frame_manager.go
  common/frame_session.go
Labels: ci

#220 Revert "Remove BASEREV and new-from-rev from CI workflow"
  .github/workflows/all.yaml
Labels: ci

#221 Move injected script to ExecutionContext
  common/errors.go
  common/execution_context.go
  common/injected_script.go
Labels: tests, refactor

#224 Refactor: errorFromDOMError with test
  common/element_handle.go
  common/element_handle_test.go
  common/helpers.go
Labels: refactor

#227 Bump CI test run timeouts
  .github/workflows/all.yaml
Labels: ci

#225 Refactor QueryAll JS and Go funcs
  common/element_handle.go
  common/js/query_all.js
  common/js/selectors.go
Labels: refactor

#229 Unit test queryAll
  common/element_handle.go
  common/element_handle_test.go
Labels: tests

#238 Fix contextWithDoneChan possible goroutine leak
  common/context.go
  common/context_test.go
Labels: bug

#244 Add test short skip for slow mo tests
  tests/launch_options_slowmo_test.go
Labels: tests
