Repository grafana/xk6-browser, pull requests merged in 2023-12, with the labels that each got.

#1137 Provide a better error message when Chromium isn't found
  chromium/browser_type.go
  chromium/browser_type_test.go
Labels: ux

#1142 Bump k6 to 0.48.1-973e442
  go.mod
  go.sum
  tests/tracing_test.go
Labels: dependencies

#1141 Refactor TraceNavigation
  common/frame_session.go
  common/trace.go
  tests/tracing_test.go
  trace/trace.go
Labels: refactor
