Repository grafana/xk6-browser, pull requests merged in 2023-08, with the labels that each got.

#993 Drop getting k6 version "latest" from CI tasks
  .github/workflows/e2e.yml
  go.mod
  go.sum
Labels: ci, k6-core-compatibility

#1010 Fix FrameSession.executionContextForID
  common/frame_session.go
Labels: bug

#1021 Fix WebVitals no interaction test
  tests/webvital_test.go
Labels: bug, tests
