Repository grafana/xk6-browser, pull requests merged in 2023-01, with the labels that each got.

#702 Expose VU to the mapping layer
  browser/mapping.go
  browser/mapping_test.go
  browser/module.go
  browser/module_test.go
Labels: blocked, async, k6-core-compatibility, mapping

#712 Fix lifecycle tests parallelism bug
  tests/lifecycle_wait_test.go
Labels: bug, tests

#713 Fix dismiss dialog test bug
  tests/frame_test.go
Labels: bug, tests

#714 Fix frame manager navigate frame bug
  common/frame_manager.go
Labels: bug

#716 Add a testbrowser function runner helper
  go.mod
  go.sum
  tests/test_browser.go
Labels: tests

#723 Remove await method from testBrowser
  tests/launch_options_slowmo_test.go
  tests/lifecycle_wait_test.go
  tests/test_browser.go
Labels: refactor

#741 Revert env var that disables test runs
  browser/module.go
  browser/module_test.go
Labels: high prio, k6-core-compatibility

#724 Release v0.8.0
  browser/module.go
  release notes/v0.8.0.md
Labels: documentation

#743 Revert the update of some of the dependency
  go.mod
  go.sum
Labels: k6-core-compatibility
