Repository grafana/xk6-browser, pull requests merged in 2023-06, with the labels that each got.

#916 Remove some of the http metrics
  common/network_manager.go
  common/network_manager_test.go
  k6ext/metrics.go
Labels: breaking change

#910 Abstract `browser` and `browserType` from JS API
  api/browser_type.go
  browser/mapping.go
  browser/mapping_test.go
  browser/module.go
  browser/module_test.go
  browser/modulevu.go
  browser/registry.go
  chromium/browser_type.go
  common/frame_session.go
  common/network_manager.go
  examples/browser_on.js
  examples/colorscheme.js
  examples/device_emulation.js
  examples/elementstate.js
  examples/evaluate.js
  examples/fillform.js
  examples/getattribute.js
  examples/grant_permission.js
  examples/hosts.js
  examples/keyboard.js
  examples/launch_naked.js
  examples/locator.js
  examples/locator_pom.js
  examples/mouse.js
  examples/multiple-scenario.js
  examples/querying.js
  examples/screenshot.js
  examples/touchscreen.js
  examples/waitforfunction.js
  k6ext/context.go
  tests/browser_test.go
  tests/browser_type_test.go
  tests/test_browser.go
Labels: user experience, breaking change

#923 Remove browser module Version
  browser/module.go
Labels: bug, breaking change

#936 Remove the BaseEventEmitter from browser
  common/browser.go
Labels: maintenance

#935 Refactor integration test browser
  common/network_manager_test.go
  k6ext/k6test/vu.go
  tests/browser_context_options_test.go
  tests/browser_context_test.go
  tests/browser_test.go
  tests/browser_type_test.go
  tests/element_handle_test.go
  tests/frame_manager_test.go
  tests/frame_test.go
  tests/launch_options_slowmo_test.go
  tests/lifecycle_wait_test.go
  tests/network_manager_test.go
  tests/page_test.go
  tests/test_browser.go
  tests/test_browser_test.go
  tests/webvital_test.go
Labels: tests, refactor

#943 Fix race condition in navigation (and lifecycle events)
  chromium/browser_type.go
  common/browser.go
  common/browser_test.go
  common/frame.go
  common/frame_manager.go
  common/page.go
  common/types.go
  tests/launch_options_slowmo_test.go
  tests/page_test.go
Labels: bug

#949 Report Web Vital metrics on every chance
  common/js/web_vital_init.js
Labels: bug

#952 Fix web vital test bug while receiving metrics
  tests/static/usual.html
  tests/webvital_test.go
Labels: bug, tests
