Repository grafana/xk6-browser, pull requests merged in 2023-05, with the labels that each got.

#849 Update nil session log warn to debug in page attach
  common/browser.go
Labels: user experience

#899 Refactor/pid registry
  browser/mapping.go
  browser/module.go
  browser/modulevu.go
  registry/pid.go
  registry/pid_test.go
Labels: refactor

#904 Fix race condition in web vital unit test
  tests/webvital_test.go
Labels: bug, tests
